FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["PetConecta.csproj", "./"]
RUN dotnet restore "./PetConecta.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "PetConecta.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PetConecta.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PetConecta.dll"]
